version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: safootwear_db
      POSTGRES_USER: safootwear_user
      POSTGRES_PASSWORD: safootwear_user1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
