version: '3'

services:
  web:
    build: .
    image: shinas07/ecommerce:latest
    container_name: ecommerce_container
      
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env 

  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: safootwear_db
      POSTGRES_USER: safootwear_user
      POSTGRES_PASSWORD: safootwear_user1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


