# Generated by Django 5.0.2 on 2024-03-09 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0002_productoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
