# Generated by Django 5.0.2 on 2024-02-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
