# Generated by Django 5.0.2 on 2024-02-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='decription',
            new_name='description',
        ),
    ]
