# Generated by Django 5.0.2 on 2024-02-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_rename_decription_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category_name',
            new_name='category_name',
        ),
    ]
