# Generated by Django 5.0.2 on 2024-02-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0004_category_is_listed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'category'},
        ),
    ]
