# Generated by Django 5.0.2 on 2024-02-27 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_address_address_address_line_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line_2',
            new_name='House_no',
        ),
    ]
