# Generated by Django 5.0.2 on 2024-02-27 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_rename_address_line_2_address_house_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line_1',
            new_name='address',
        ),
    ]
