# Generated by Django 5.0.2 on 2024-03-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_rename_address_line_1_address_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_delete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
