# Generated by Django 5.0.2 on 2024-03-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_coupen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupen',
            new_name='Coupon',
        ),
    ]
