# Generated by Django 5.0.2 on 2024-03-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_cart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_applied',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
