# Generated by Django 5.0.2 on 2024-03-19 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0007_cart_total_amount'),
        ('Products', '0009_product_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_size_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.productsizecolor'),
        ),
    ]
