# Generated by Django 5.0.2 on 2024-02-29 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='Product',
            new_name='product',
        ),
    ]
