# Generated by Django 5.0.2 on 2024-03-01 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_order_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_cancelled',
        ),
    ]
