# Generated by Django 5.0.2 on 2024-03-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_remove_order_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='is_cancelled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
