# Generated by Django 5.0.2 on 2024-03-03 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_remove_order_products_remove_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='is_cancelled',
        ),
    ]
