# Generated by Django 5.0.2 on 2024-03-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_remove_orderproduct_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
