# Generated by Django 5.0.2 on 2024-03-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0011_orderproduct_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('Razorpay', 'Razorpay')], default=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('Razorpay', 'Razorpay')], max_length=20),
        ),
    ]
