# Generated by Django 5.0.2 on 2024-03-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0013_alter_orderproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
