# Generated by Django 5.0.2 on 2024-03-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0019_remove_orderproduct_cancellation_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='processed_for_refund',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
