# Generated by Django 5.0.2 on 2024-03-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0021_remove_orderproduct_processed_for_refund_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
