# Generated by Django 5.0.2 on 2024-03-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0023_remove_order_address_name_order_house_no_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
