# Generated by Django 5.0.2 on 2024-02-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_stock_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
