# Generated by Django 5.0.2 on 2024-02-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_stock_remove_product_full_view_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_view_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='left_view_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='right_view_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
