# Generated by Django 5.0.2 on 2024-02-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_remove_product_color_variant_remove_product_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsizecolor',
            name='is_unlisted',
            field=models.BooleanField(default=False),
        ),
    ]
